# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MuI5He06Yq37HhxBXZQbSy-w_6htkBOE

# MiniProject1
"""

import pandas as pd
import numpy as np
user_profile = pd.read_csv('userprofile.csv', skiprows=1, delimiter=';', names=['userID', 'Name'])
ratings = pd.read_csv('ratings.csv', skiprows=1, delimiter=';', names=['userID', 'placeID', 'rating', 'food_rating', 'service_rating'])
places = pd.read_csv('places.csv', skiprows=1, delimiter=';', names=['placeID', 'name'])
cuisine = pd.read_csv('place_cuisine.csv', skiprows=1, delimiter=';', names=['placeID', 'cuisine'])
# Step 2: Merge Datasets
print("User Profile Columns:", user_profile.columns)
print("Ratings Columns:", ratings.columns)
print("Places Columns:", places.columns)
print("Cuisine Columns:", cuisine.columns)

# If the 'user_id' column is present in ratings, adjust the merging accordingly
if 'userID' in ratings.columns:
    merged_data = pd.merge(ratings, user_profile, on='userID')
    merged_data = pd.merge(merged_data, places, on='placeID')
    merged_data = pd.merge(merged_data, cuisine, on='placeID')
else:
    print("No 'user_id' column found in ratings.")

# Step 3: Construct a User Ratings Dictionary
user_ratings = {}

for index, row in merged_data.iterrows():
    userID = row['userID']
    cuisine = row['cuisine']
    rating = row['rating']

    if userID not in user_ratings:
        user_ratings[userID] = {}

    user_ratings[userID][cuisine] = rating

# Example: Print the user ratings for each user
for userID, ratings_dict in user_ratings.items():
    print(f"User {userID} Ratings: {ratings_dict}")

# Step 4: Calculate Overall Cuisine Rating
random_number = np.random.uniform(0, 10, len(merged_data))
merged_data['overall_cuisine_rating'] = (
    (merged_data['rating'] * 1.4 + merged_data['food_rating'] * 2.5 + merged_data['service_rating'] * 1.8 + random_number)
    * merged_data.groupby(['placeID', 'cuisine']).cumcount()  # Rank of the cuisine for that restaurant
)


# Aggregate results based on user and cuisine
user_cuisine_ratings = merged_data.groupby(['userID', 'cuisine'])['overall_cuisine_rating'].mean().reset_index()

# Print the results
print(user_cuisine_ratings)

#step5
merged_data['restaurant_type'] = np.where(merged_data['cuisine'].isnull(), 'Regular Food', 'Specialized Cuisine')
user_restaurant_type_ratings = merged_data.groupby(['userID', 'restaurant_type'])['overall_cuisine_rating'].mean().reset_index()

print(user_restaurant_type_ratings)

#step6

# Assuming you have loaded your place_cuisine.csv file into the place_cuisine DataFrame
place_cuisine = pd.read_csv('place_cuisine.csv', skiprows=1, delimiter=';', names=['placeID', 'cuisine'])

# Sort the place_cuisine DataFrame by 'placeID' and 'cuisine' to ensure proper ordering
place_cuisine_sorted = place_cuisine.sort_values(by=['placeID', 'cuisine'])

# Calculate the normalized rank for each cuisine
place_cuisine_sorted['normalized_rank'] = 2.0 - (place_cuisine_sorted.groupby('placeID').cumcount() / place_cuisine_sorted.groupby('placeID').cumcount().max())

# Print the resulting DataFrame with cuisine ranks
print(place_cuisine_sorted[['placeID', 'cuisine', 'normalized_rank']])

#step7
user_ratings_dict = {}

for index, row in merged_data.iterrows():
    user_name = row['Name']
    cuisine = row['cuisine']
    overall_rating = (row['rating'] + row['food_rating'] + row['service_rating']) / 3.0

    if user_name not in user_ratings_dict:
        user_ratings_dict[user_name] = {}

    if cuisine not in user_ratings_dict[user_name]:
        user_ratings_dict[user_name][cuisine] = []

    user_ratings_dict[user_name][cuisine].append(overall_rating)

# Calculate average ratings for each cuisine for each user
for user_name, cuisine_ratings in user_ratings_dict.items():
    for cuisine, ratings in cuisine_ratings.items():
        avg_rating = sum(ratings) / len(ratings)
        user_ratings_dict[user_name][cuisine] = avg_rating

# Print the resulting dictionary
for user_name, cuisine_ratings in user_ratings_dict.items():
    print(f'"{user_name}": {cuisine_ratings},')

from math import sqrt

user_ratings_dict={"UBEYDULLAH OSMAN": {'Fast_Food': 2.0, 'Mexican': 1.3333333333333333, 'Seafood': 1.6666666666666667},
"SUHEYB": {'Fast_Food': 1.111111111111111, 'Mexican': 1.5, 'Cafeteria': 1.5, 'Contemporary': 1.6666666666666667, 'Seafood': 2.0, 'Burgers': 0.6666666666666666, 'Pizzeria': 1.0},
"MUHAMMED HAMZA": {'Fast_Food': 0.8333333333333333, 'Mexican': 1.0, 'Cafeteria': 0.8333333333333333, 'Contemporary': 0.6666666666666666, 'Bar': 0.6666666666666666, 'Bar_Pub_Brewery': 0.6666666666666666, 'Pizzeria': 0.3333333333333333, 'Seafood': 0.0, 'Cafe-Coffee_Shop': 1.0},
"ABDULKADIR KAAN": {'Fast_Food': 0.6666666666666666, 'Mexican': 1.8333333333333335, 'Seafood': 1.0},
"UBEYDULLAH": {'Fast_Food': 2.0, 'Mexican': 2.0, 'Bar': 2.0, 'Bar_Pub_Brewery': 2.0},
"ELIF DEVELI": {'Fast_Food': 1.5, 'Mexican': 1.5555555555555554, 'Cafeteria': 0.0, 'Contemporary': 2.0, 'Chinese': 1.1666666666666665, 'Seafood': 1.3333333333333333, 'Bar': 0.5, 'Bar_Pub_Brewery': 0.0},
"ENES TARIK": {'Fast_Food': 2.0, 'Mexican': 1.0, 'Cafeteria': 0.888888888888889, 'Contemporary': 0.0, 'Chinese': 1.3333333333333333, 'Bar': 0.5, 'Bar_Pub_Brewery': 0.0, 'Seafood': 1.3333333333333333, 'Cafe-Coffee_Shop': 1.6666666666666667, 'Italian': 0.3333333333333333, 'International': 2.0},
"TALHA YASIR": {'Fast_Food': 2.0, 'Mexican': 1.8333333333333333, 'Seafood': 0.0, 'Bar': 1.6666666666666665, 'Bar_Pub_Brewery': 2.0, 'Cafe-Coffee_Shop': 1.6666666666666667, 'Cafeteria': 1.6666666666666667},
"BEDIRHAN": {'Fast_Food': 0.5, 'Cafeteria': 0.8333333333333333, 'Contemporary': 0.6666666666666666, 'Burgers': 0.0, 'Pizzeria': 1.3333333333333333, 'Mexican': 1.0, 'Bar': 1.3333333333333333},
"ZEYNEP": {'Fast_Food': 2.0, 'Mexican': 1.5833333333333333, 'Cafeteria': 0.6666666666666666, 'Contemporary': 0.6666666666666666, 'Bar': 2.0, 'Bar_Pub_Brewery': 2.0},
"SENA NUR": {'Fast_Food': 0.0, 'Mexican': 1.0, 'Cafeteria': 1.0, 'Contemporary': 1.0, 'Bar': 1.5, 'Bar_Pub_Brewery': 1.0, 'International': 1.6666666666666667},
"MERYEM": {'Fast_Food': 2.0, 'Mexican': 1.9166666666666667, 'Chinese': 2.0, 'Bar': 2.0, 'Bar_Pub_Brewery': 2.0},
"TUNAHAN": {'Fast_Food': 2.0, 'Mexican': 0.6666666666666666, 'Japanese': 2.0, 'Pizzeria': 1.0, 'Cafe-Coffee_Shop': 2.0, 'Cafeteria': 2.0, 'Bar': 2.0, 'Bar_Pub_Brewery': 2.0, 'International': 2.0, 'Burgers': 2.0, 'Italian': 2.0},
"SAIT": {'Fast_Food': 0.0, 'Mexican': 1.4, 'Seafood': 1.8333333333333335, 'Cafeteria': 1.0, 'Contemporary': 1.0, 'Chinese': 1.0, 'Bar': 0.5, 'Bar_Pub_Brewery': 1.0, 'Cafe-Coffee_Shop': 2.0, 'Italian': 2.0, 'International': 1.0},
"MEHMET VELI": {'Fast_Food': 1.5, 'Cafeteria': 0.0, 'Contemporary': 0.0, 'Bar': 1.6666666666666667, 'Chinese': 1.3333333333333333, 'Italian': 0.3333333333333333, 'International': 0.0},
"BEHIYE MERVE": {'Fast_Food': 1.6666666666666667, 'Mexican': 1.3333333333333333, 'Cafeteria': 1.3333333333333333, 'Contemporary': 1.3333333333333333, 'Bar': 1.1666666666666665, 'Bar_Pub_Brewery': 1.0, 'Seafood': 0.3333333333333333, 'Cafe-Coffee_Shop': 1.3333333333333333},
"OMER TORAMAN": {'Fast_Food': 2.0, 'Mexican': 1.1666666666666665, 'Seafood': 2.0, 'Cafeteria': 0.6666666666666666, 'Contemporary': 0.0, 'Bar': 1.5, 'Bar_Pub_Brewery': 1.6666666666666667, 'Italian': 1.6666666666666667},
"FURKAN KACAN": {'Fast_Food': 1.3333333333333333, 'Seafood': 2.0, 'Cafeteria': 2.0, 'Contemporary': 2.0, 'Mexican': 2.0, 'Chinese': 1.6666666666666667, 'Bar': 2.0, 'Bar_Pub_Brewery': 2.0, 'Italian': 2.0, 'International': 2.0},
"EMRE KAYAR": {'Fast_Food': 1.0, 'Seafood': 1.1666666666666667, 'Cafeteria': 0.6666666666666666, 'Japanese': 1.5, 'Chinese': 1.0, 'American': 2.0, 'Bar': 1.6666666666666667},
"MUHAMMET SADIK": {'Fast_Food': 0.0, 'Mexican': 0.0, 'Cafeteria': 0.0, 'Pizzeria': 0.0, 'Bar': 0.0, 'Bar_Pub_Brewery': 0.0, 'American': 0.0},
"AHMET BURAK": {'Fast_Food': 0.0, 'Mexican': 0.0, 'Seafood': 0.0, 'Cafeteria': 0.0, 'Contemporary': 0.0, 'Pizzeria': 0.0, 'Chinese': 0.0, 'Bar': 0.0, 'Bar_Pub_Brewery': 0.0, 'Italian': 0.0},
"MERT OKUMUS": {'Fast_Food': 1.0, 'Seafood': 1.0, 'Cafeteria': 0.0, 'Contemporary': 0.0, 'Pizzeria': 1.0, 'Chinese': 0.8333333333333333, 'Italian': 0.6666666666666666, 'Mexican': 0.6666666666666666, 'American': 1.0},
"MERVE NUR": {'Fast_Food': 0.0, 'Bar': 0.3333333333333333, 'Bar_Pub_Brewery': 0.3333333333333333, 'Mexican': 1.1666666666666665, 'Cafeteria': 0.3333333333333333},
"MEHMET": {'Fast_Food': 2.0, 'Mexican': 2.0, 'Cafeteria': 2.0, 'Contemporary': 2.0, 'Pizzeria': 2.0, 'Chinese': 2.0, 'Italian': 1.0, 'American': 1.0},
"SAMIL": {'Fast_Food': 1.3333333333333333, 'Mexican': 1.0, 'Seafood': 1.6666666666666667, 'Cafeteria': 1.0, 'Contemporary': 1.3333333333333333, 'Chinese': 1.3333333333333333, 'Italian': 1.3333333333333333, 'International': 1.6666666666666667, 'Burgers': 1.6666666666666667, 'Bar': 1.3333333333333333},
"OMER ASLAN": {'Fast_Food': 1.3333333333333333, 'Cafeteria': 1.0, 'Chinese': 0.6666666666666666, 'Pizzeria': 1.6666666666666667, 'Bar': 1.3333333333333335, 'Bar_Pub_Brewery': 1.0, 'Burgers': 1.6666666666666667, 'American': 1.3333333333333333},
"HAYRIYE NUR": {'Fast_Food': 1.8333333333333335, 'Pizzeria': 1.6666666666666665, 'Mexican': 1.5, 'Cafeteria': 1.6666666666666665, 'Cafe-Coffee_Shop': 1.3333333333333333, 'Chinese': 2.0, 'American': 2.0},
"MERT FURKAN": {'Fast_Food': 1.6666666666666665, 'Cafeteria': 0.8333333333333333, 'Seafood': 1.0, 'Mexican': 1.3333333333333333, 'Cafe-Coffee_Shop': 1.3333333333333333, 'American': 1.0, 'Bar': 1.3333333333333333},
"FEYYAZ": {'Fast_Food': 1.0, 'Japanese': 1.0, 'Mexican': 1.0, 'Pizzeria': 1.0, 'Bar': 1.0, 'Bar_Pub_Brewery': 1.0, 'Chinese': 0.0, 'American': 1.0},
"IREM": {'Fast_Food': 1.0, 'Chinese': 1.0, 'Bar': 1.0, 'Bar_Pub_Brewery': 1.0, 'American': 1.0, 'Japanese': 1.0, 'Mexican': 1.0},
"MAHMUT SAMI": {'Fast_Food': 1.0, 'Mexican': 0.3333333333333333, 'Bar': 1.111111111111111, 'International': 1.0, 'Cafeteria': 1.0},
"BIRKAN BULENT": {'Fast_Food': 1.3333333333333333, 'Seafood': 1.0, 'Bar': 1.3333333333333333, 'Cafeteria': 1.8333333333333335, 'American': 1.0},
"ELIF YASAR": {'Fast_Food': 1.6666666666666667, 'Mexican': 1.9166666666666667, 'Seafood': 2.0, 'Pizzeria': 1.3333333333333333, 'Chinese': 2.0, 'Bar': 1.3333333333333333, 'International': 2.0, 'American': 2.0},
"HASAN FURKAN": {'Fast_Food': 2.0, 'Cafeteria': 1.6666666666666665, 'Mexican': 2.0, 'Bar': 2.0, 'Bar_Pub_Brewery': 2.0, 'International': 2.0, 'Breakfast-Brunch': 2.0},
"YUSUF": {'Fast_Food': 2.0, 'Mexican': 1.4444444444444444, 'Chinese': 1.3333333333333333, 'Seafood': 1.6666666666666667, 'Cafe-Coffee_Shop': 2.0, 'Cafeteria': 2.0, 'International': 0.0, 'Bar_Pub_Brewery': 1.6666666666666667},
"AHMET CIFTKAYA": {'Fast_Food': 1.0, 'Mexican': 1.222222222222222, 'Bar': 1.1666666666666665, 'Bar_Pub_Brewery': 1.0, 'Cafeteria': 1.0, 'International': 2.0},
"SUMEYYE SENA": {'Mexican': 2.0, 'Cafeteria': 2.0, 'Seafood': 2.0, 'Bar': 2.0},
"SERHAT": {'Mexican': 1.3333333333333333, 'Seafood': 1.6666666666666667, 'Cafeteria': 1.5, 'Contemporary': 1.6666666666666667, 'Chinese': 1.6666666666666667, 'Fast_Food': 1.3333333333333333, 'Pizzeria': 1.3333333333333333},
"IBRAHIM SHABAN": {'Mexican': 0.9333333333333332, 'Seafood': 1.5, 'Cafeteria': 1.3333333333333333, 'Contemporary': 2.0, 'Chinese': 1.3333333333333333, 'Cafe-Coffee_Shop': 1.0, 'Bar': 1.0, 'Bar_Pub_Brewery': 1.0},
"MOHAMMADALI": {'Mexican': 0.26666666666666666, 'Japanese': 0.0, 'Pizzeria': 0.0, 'Cafeteria': 0.0, 'Fast_Food': 0.0, 'American': 0.5},
"DILAN": {'Mexican': 1.2222222222222223, 'Seafood': 1.0, 'Pizzeria': 1.3333333333333333, 'Bar': 1.1666666666666665, 'Bar_Pub_Brewery': 1.0, 'Chinese': 1.6666666666666667, 'International': 1.6666666666666667},
"SEKVAN": {'Mexican': 2.0, 'Chinese': 0.0, 'Fast_Food': 2.0, 'Pizzeria': 2.0, 'Bar': 1.6666666666666667, 'American': 1.3333333333333333, 'Cafeteria': 0.0},
"AHMET COVUT": {'Mexican': 1.75, 'Seafood': 2.0, 'Bar': 1.4444444444444444, 'Cafeteria': 1.3333333333333333, 'Chinese': 2.0, 'International': 1.6666666666666667},
"ILAYDA": {'Mexican': 0.6666666666666666, 'Cafeteria': 2.0, 'Seafood': 2.0, 'Burgers': 1.0, 'Fast_Food': 1.0, 'Italian': 1.0, 'Japanese': 1.6666666666666667},
"AHMET MANSUR": {'Mexican': 1.5833333333333333, 'Japanese': 2.0, 'Fast_Food': 1.3333333333333333, 'Cafeteria': 1.8333333333333335, 'Seafood': 2.0, 'Burgers': 1.3333333333333333, 'Pizzeria': 1.0, 'Bar': 1.8333333333333333, 'Bar_Pub_Brewery': 2.0, 'Breakfast-Brunch': 1.6666666666666667, 'American': 2.0},
"WAAEL YOUNUS KHALAF": {'Mexican': 0.6666666666666666, 'Fast_Food': 0.6666666666666666, 'Seafood': 0.6666666666666666, 'Pizzeria': 1.0, 'Cafe-Coffee_Shop': 0.6666666666666666, 'Cafeteria': 0.6666666666666666, 'International': 0.3333333333333333, 'Breakfast-Brunch': 0.3333333333333333},
"ISMAIL": {'Mexican': 0.5, 'Bar': 2.0, 'Bar_Pub_Brewery': 2.0, 'Bakery': 1.6666666666666667, 'Cafeteria': 1.6666666666666667, 'International': 2.0, 'American': 0.3333333333333333},
"AYSE SIDIKA": {'Mexican': 1.0, 'Cafeteria': 1.2222222222222223, 'Seafood': 1.3333333333333333, 'Bar': 1.6666666666666665, 'Cafe-Coffee_Shop': 1.3333333333333333, 'Bar_Pub_Brewery': 2.0, 'Chinese': 1.0, 'Breakfast-Brunch': 1.0, 'Japanese': 2.0},
"EDANUR": {'Seafood': 0.6666666666666666, 'Chinese': 1.3333333333333333, 'Bar': 1.0, 'Bar_Pub_Brewery': 1.3333333333333333},
"BERKAY": {'Seafood': 1.0, 'Cafeteria': 1.3333333333333333, 'Contemporary': 1.3333333333333333, 'Chinese': 1.0, 'Fast_Food': 1.3333333333333333, 'Pizzeria': 1.3333333333333333},
"HEBA AHMED HAMED SHAKER": {'Seafood': 1.3333333333333333, 'Cafeteria': 1.3333333333333333, 'Contemporary': 1.3333333333333333, 'Mexican': 0.0, 'Bar': 2.0, 'Bar_Pub_Brewery': 2.0},
"AMROU": {'Seafood': 1.0, 'Mexican': 2.0, 'Cafeteria': 2.0, 'Contemporary': 2.0, 'Breakfast-Brunch': 2.0, 'Bar_Pub_Brewery': 2.0, 'American': 2.0},
"YUSUF ZEYDAN": {'Seafood': 2.0, 'Mexican': 1.5, 'Bar': 1.8333333333333335, 'Bar_Pub_Brewery': 2.0, 'Cafeteria': 1.3333333333333335},
"OGUZ YASIN": {'Seafood': 2.0, 'Chinese': 1.0, 'Fast_Food': 2.0, 'Pizzeria': 2.0, 'Italian': 0.6666666666666666, 'Mexican': 2.0, 'American': 1.3333333333333333, 'Cafeteria': 0.0},
"SINAN": {'Seafood': 1.8333333333333335, 'Cafeteria': 1.5, 'Contemporary': 1.0, 'Mexican': 2.0, 'Bar': 1.8333333333333335, 'Bar_Pub_Brewery': 1.6666666666666667, 'Italian': 2.0},
"FEYYAZ ASLAN": {'Seafood': 0.0, 'Pizzeria': 0.0, 'Cafeteria': 0.0, 'Fast_Food': 0.0, 'Chinese': 0.0, 'Breakfast-Brunch': 0.0, 'American': 0.0, 'Bar': 0.0, 'Japanese': 0.0, 'Mexican': 0.0},
"EREN": {'Seafood': 0.0, 'Cafeteria': 0.0, 'Bar': 0.0, 'Bar_Pub_Brewery': 0.0, 'Mexican': 0.0, 'International': 0.0, 'Breakfast-Brunch': 0.0, 'American': 0.0},
"ZEYNEP MERVE": {'Mexican': 0.6666666666666666, 'Chinese': 2.0, 'Seafood': 1.6666666666666667, 'Bar': 1.3333333333333333, 'Bar_Pub_Brewery': 1.3333333333333333},
"SELMA": {'Mexican': 0.6666666666666666, 'Cafeteria': 0.888888888888889, 'Family': 1.3333333333333333, 'Contemporary': 1.6666666666666667, 'Italian': 0.8333333333333333, 'Bar': 0.7777777777777777, 'Bar_Pub_Brewery': 1.1666666666666665, 'Seafood': 1.0},
"FADDALE": {'Mexican': 0.7222222222222222, 'Pizzeria': 0.6666666666666666},
"ABDULSAMET": {'Mexican': 1.0833333333333335, 'Pizzeria': 1.0, 'Regional': 0.3333333333333333},
"CEMALETTIN": {'Mexican': 1.1666666666666667, 'Pizzeria': 2.0, 'Armenian': 1.6666666666666667},
"MUHAMMED FARUK": {'Mexican': 1.2777777777777777, 'Pizzeria': 1.3333333333333333, 'Armenian': 1.3333333333333333},
"ABDURRAHMAN TALHA": {'Mexican': 1.3333333333333333, 'Armenian': 1.3333333333333333, 'Fast_Food': 0.6666666666666666},
"MAHMUT GAZI": {'Mexican': 1.0555555555555556, 'Pizzeria': 1.0},
"HATICE SENA": {'Mexican': 1.4, 'Regional': 1.3333333333333333, 'Armenian': 1.6666666666666667},
"HUZEYFE": {'Mexican': 0.0, 'Pizzeria': 2.0, 'Fast_Food': 0.0},
"ZERAY": {'Mexican': 1.3333333333333333, 'Pizzeria': 1.6666666666666667, 'Fast_Food': 2.0},
"HAZEL": {'Mexican': 1.777777777777778},
"SEDA": {'Mexican': 0.4, 'Regional': 0.6666666666666666, 'Fast_Food': 0.0},
"MERT CAKIRUYLASI": {'Mexican': 0.0},
"EMIRCAN": {'Mexican': 0.16666666666666666, 'Pizzeria': 0.0, 'Regional': 0.0, 'Fast_Food': 0.0},
"MUSTAFA ZAHID": {'Mexican': 1.0, 'Fast_Food': 1.3333333333333333},
"MUHAMMED SALIH": {'Pizzeria': 2.0, 'Mexican': 2.0},
"ELIF HANDE": {'Pizzeria': 1.0, 'Mexican': 1.3333333333333333},
"MUHAMMET ENES": {'Mexican': 1.1666666666666667, 'Fast_Food': 1.0},
"MUMTAZ OMER": {'Cafeteria': 2.0, 'American': 1.3333333333333333, 'International': 2.0, 'Family': 2.0},
"MEHMET SAID": {'Cafeteria': 0.6666666666666666, 'International': 2.0, 'Mexican': 2.0, 'Bar': 0.0, 'Vietnamese': 0.0, 'Italian': 0.0},
"SUMEYYE": {'Cafeteria': 0.3333333333333333, 'Family': 1.6666666666666667, 'Mexican': 1.6666666666666667},
"SERKAN EKREM": {'Cafeteria': 1.3333333333333333, 'Mexican': 1.3333333333333335, 'Japanese': 0.3333333333333333, 'Family': 1.6666666666666667},
"HAYRULLAH": {'Cafeteria': 1.0, 'Family': 2.0, 'Italian': 1.6666666666666667},
"MEHMET ALI": {'American': 0.0, 'Family': 0.0, 'Bar': 0.0, 'Bar_Pub_Brewery': 0.0, 'Fast_Food': 0.6666666666666666},
"MERVE FIDAN": {'American': 1.0, 'International': 2.0, 'Mexican': 1.5, 'Family': 1.6666666666666667},
"SINAN BURAK": {'American': 2.0, 'International': 2.0, 'Family': 2.0, 'Fast_Food': 0.0},
"EMRE YIGIT": {'International': 2.0, 'Bar': 2.0, 'Bar_Pub_Brewery': 2.0, 'Mexican': 2.0},
"BILAL": {'International': 2.0, 'Bar': 1.0, 'Bar_Pub_Brewery': 1.0, 'Vietnamese': 0.0, 'Fast_Food': 2.0, 'Japanese': 0.6666666666666666},
"MUSTAFA": {'International': 2.0, 'Family': 2.0, 'Mexican': 0.6666666666666666, 'Mediterranean': 0.6666666666666666, 'Burgers': 0.6666666666666666, 'Japanese': 1.3333333333333333},
"MUSTAFA ABDULBAKI": {'International': 2.0, 'Family': 1.6666666666666667, 'Fast_Food': 1.0},
"HAKAN": {'Family': 1.0, 'Bar': 0.3333333333333333, 'Bar_Pub_Brewery': 0.3333333333333333},
"HIKMETHAN": {'Family': 2.0, 'Mexican': 1.6666666666666667, 'Mediterranean': 1.6666666666666667, 'Burgers': 1.6666666666666667, 'Fast_Food': 1.0},
"MUSTAFA CEBECI": {'Family': 1.6666666666666667, 'Bar': 2.0, 'Bar_Pub_Brewery': 2.0, 'Italian': 1.3333333333333333, 'Fast_Food': 2.0},
"IPEK": {'Mexican': 1.3333333333333333, 'Italian': 2.0},
"SELCUK": {'Mexican': 0.16666666666666666},
"FURKAN FATIH": {'Mexican': 1.3333333333333335, 'Italian': 0.6666666666666666},
"MUHAMMED EMIN": {'Mexican': 1.3333333333333333, 'Italian': 1.6666666666666667},
"EBUZER": {'Mexican': 0.6666666666666666, 'Fast_Food': 1.6666666666666667},
"FURKAN UNLU": {'Bar': 0.0, 'Bar_Pub_Brewery': 0.0, 'Mexican': 1.0, 'Bakery': 0.6666666666666666, 'Cafeteria': 0.6666666666666666, 'Burgers': 0.3333333333333333, 'Seafood': 1.0, 'Pizzeria': 2.0, 'American': 1.0, 'Game': 1.0},
"YUSUF BURAK": {'Bar': 1.3333333333333335, 'Bar_Pub_Brewery': 0.0, 'Seafood': 2.0, 'Cafeteria': 2.0, 'Contemporary': 2.0},
"OZLEM": {'Bar': 0.8888888888888888, 'Bar_Pub_Brewery': 0.6666666666666666, 'Seafood': 1.0, 'Cafeteria': 1.0, 'Contemporary': 1.0},
"MUHAMMED YASIN": {'Bar': 0.3333333333333333, 'Bar_Pub_Brewery': 0.3333333333333333, 'Seafood': 0.0},
"BELAL": {'Bar': 1.5555555555555556, 'Bar_Pub_Brewery': 2.0, 'Seafood': 0.3333333333333333},
"MOHAMMED MONEER SAEED": {'Bar': 0.3333333333333333, 'Bar_Pub_Brewery': 0.3333333333333333, 'Mexican': 0.0, 'Seafood': 1.3333333333333333, 'Pizzeria': 1.3333333333333333, 'American': 1.6666666666666667, 'Game': 1.6666666666666667, 'International': 1.0},
"NURSENA": {'Bar': 2.0, 'Bar_Pub_Brewery': 2.0, 'Mexican': 1.6666666666666667, 'Burgers': 0.5, 'Pizzeria': 0.0, 'American': 1.0, 'Game': 1.0, 'International': 2.0},
"MUHAMMED CAN": {'Mexican': 0.0, 'American': 0.3333333333333333, 'Game': 0.3333333333333333, 'Bar': 0.0, 'International': 0.0, 'Burgers': 0.0},
"SERHAN": {'Bakery': 1.6666666666666667, 'Cafeteria': 1.6666666666666667, 'Burgers': 1.0, 'Pizzeria': 1.6666666666666667, 'American': 1.0, 'Game': 1.0},
"BETUL SEYMA": {'Bakery': 1.0, 'Cafeteria': 1.0, 'Seafood': 1.0, 'Pizzeria': 1.0, 'American': 1.0, 'Game': 1.0, 'Bar': 1.0, 'International': 1.3333333333333335, 'Burgers': 1.3333333333333333},
"OMER FARUK KURT": {'Bakery': 2.0, 'Cafeteria': 2.0, 'Burgers': 0.6666666666666666, 'Seafood': 1.6666666666666667, 'Pizzeria': 1.3333333333333333, 'American': 2.0, 'Game': 2.0},
"ABDULLAH": {'Burgers': 1.3333333333333333, 'International': 2.0},
"YASIR": {'Seafood': 1.3333333333333333, 'Mexican': 2.0, 'Bar': 1.1666666666666665, 'Bar_Pub_Brewery': 1.3333333333333333, 'Cafeteria': 1.3333333333333333},
"NEZAR": {'Seafood': 0.0, 'Bar': 0.0, 'Bar_Pub_Brewery': 0.0},
"MELIKE": {'Italian': 0.0, 'Mexican': 1.3333333333333333},
"YETKIN": {'Japanese': 1.8333333333333335, 'Mexican': 1.5, 'Fast_Food': 1.6666666666666667, 'Cafeteria': 2.0, 'Seafood': 0.0, 'Contemporary': 2.0, 'Chinese': 1.6666666666666667},
"BURAK": {'Japanese': 2.0, 'Mexican': 1.7777777777777777, 'Cafeteria': 0.8333333333333333, 'Contemporary': 1.0, 'Burgers': 1.1666666666666665, 'Fast_Food': 1.3333333333333333, 'Pizzeria': 1.6666666666666667, 'Bar': 1.0, 'Seafood': 1.3333333333333333, 'American': 1.6666666666666667, 'Italian': 2.0},
"RUMEYSA": {'Japanese': 1.6666666666666667, 'Mexican': 2.0, 'Seafood': 1.0, 'Bar': 1.1666666666666667, 'Bar_Pub_Brewery': 2.0},
"DOGUKAN": {'Japanese': 1.6666666666666667, 'Seafood': 1.3333333333333333, 'Burgers': 1.3333333333333335, 'Fast_Food': 1.5, 'Pizzeria': 1.6666666666666665, 'Cafeteria': 2.0, 'Bar': 1.1666666666666667, 'Bar_Pub_Brewery': 1.1666666666666667, 'Chinese': 1.0, 'Breakfast-Brunch': 0.6666666666666666, 'American': 1.3333333333333333},
"MERVE KUCUK": {'Mexican': 0.3333333333333333, 'Seafood': 0.0, 'Burgers': 1.0, 'Fast_Food': 1.0, 'Italian': 1.0},
"MUSA": {'Mexican': 1.7777777777777777, 'Japanese': 1.6666666666666665, 'Seafood': 1.3333333333333333, 'Burgers': 1.0, 'Fast_Food': 1.0, 'Bar': 2.0, 'Bar_Pub_Brewery': 2.0, 'American': 1.6666666666666667},
"MERVE DIKMEN": {'Fast_Food': 0.0, 'Cafeteria': 0.3333333333333333, 'Burgers': 0.0, 'Bar': 0.4444444444444444, 'Bar_Pub_Brewery': 1.0, 'Chinese': 0.3333333333333333, 'Mexican': 0.3333333333333333, 'International': 1.0, 'Breakfast-Brunch': 0.3333333333333333},
"MEHMET AKIF": {'Fast_Food': 2.0, 'Japanese': 1.0, 'Contemporary': 1.3333333333333333, 'Mexican': 2.0, 'Bar': 1.8333333333333335, 'International': 2.0, 'American': 2.0},
"HALDUN MERIC": {'Cafeteria': 1.0, 'Contemporary': 1.0, 'Mexican': 1.0, 'Bar': 0.6666666666666666, 'Fast_Food': 0.0, 'Pizzeria': 0.0},
"ARDA": {'Cafeteria': 1.3333333333333335, 'Contemporary': 1.6666666666666667, 'Chinese': 1.6666666666666667, 'Bar': 1.1666666666666665, 'Fast_Food': 0.6666666666666666, 'Pizzeria': 0.6666666666666666},
"HANIFE KUBRA": {'Burgers': 0.0, 'Fast_Food': 0.0, 'Chinese': 0.0, 'Italian': 0.0, 'Mexican': 0.0, 'Bar': 0.0},
"YIGITER": {'Pizzeria': 1.4444444444444444, 'Cafeteria': 1.1666666666666665, 'Fast_Food': 1.5, 'Mexican': 2.0, 'American': 1.6666666666666667},
"DILARA": {'Pizzeria': 0.6666666666666666, 'Chinese': 1.0, 'Cafeteria': 1.0, 'Fast_Food': 1.0},
"OMER FARUK": {'Bar': 2.0, 'Mexican': 1.6666666666666667, 'Mediterranean': 1.6666666666666667, 'Burgers': 1.6666666666666667, 'Japanese': 2.0, 'Vietnamese': 2.0},
"ZELIHA": {'Bar': 1.0, 'Japanese': 1.0, 'Vietnamese': 1.3333333333333333},
"MUHAMMED HALID": {'Bar': 1.3333333333333333, 'Japanese': 1.0, 'Family': 1.0, 'Mexican': 1.0},
"MUSTAFA BAL": {'Bar': 2.0, 'Japanese': 2.0, 'Vietnamese': 2.0, 'Fast_Food': 0.0},
"ILHAN TUNAHAN": {'Mexican': 2.0, 'Mediterranean': 2.0, 'Burgers': 2.0},
"ALI SUHEYL": {'Japanese': 2.0, 'Vietnamese': 2.0, 'Fast_Food': 1.3333333333333333},
"SAMET ORKUN": {'Fast_Food': 1.3333333333333333},
"FATIH": {'Chinese': 0.6666666666666666, 'Bar': 0.8333333333333333, 'Fast_Food': 0.3333333333333333, 'Pizzeria': 0.3333333333333333},
"MOKHAMAD KHALED": {'Italian': 0.6666666666666666, 'International': 1.8333333333333335, 'Burgers': 1.1666666666666665},
"ZEYNEP ALTUN": {'Bar': 1.6666666666666667, 'Mexican': 1.3333333333333333, 'Cafeteria': 2.0},
"PELIN": {'Japanese': 0.0}}
person1 = input("İlk person ismini girin: ")
person2 = input("İkinci person ismini girin: ")
#1.similarity
def sim_distance(user_ratings_dict, person1, person2):
    # Get the list of shared_items
    si = {}
    for item in user_ratings_dict[person1]:
        if item in user_ratings_dict[person2]:
            si[item] = 1

    # if they have no ratings in common, return 0
    if len(si) == 0:
        return 0

    # Add up the squares of all the differences
    sum_of_squares = sum([pow(user_ratings_dict[person1][item] - user_ratings_dict[person2][item], 2) for item in si])

    return 1 / (1 + sqrt(sum_of_squares))

# Returns the Pearson correlation coefficient for person1 and person2
def sim_pearson(user_ratings_dict,person1,person2):
  # Get the list of mutually rated items
  si={}
  for item in user_ratings_dict[person1]:
    if item in user_ratings_dict[person2]: si[item]=1

  # if they are no ratings in common, return 0
  if len(si)==0: return 0

  # Sum calculations
  n=len(si)

  # Sums of all the preferences
  sum1=sum([user_ratings_dict[person1][it] for it in si])
  sum2=sum([user_ratings_dict[person2][it] for it in si])

  # Sums of the squares
  sum1Sq=sum([pow(user_ratings_dict[person1][it],2) for it in si])
  sum2Sq=sum([pow(user_ratings_dict[person2][it],2) for it in si])

  # Sum of the products
  pSum=sum([user_ratings_dict[person1][it]*user_ratings_dict[person2][it] for it in si])

  # Calculate r (Pearson score)
  num=pSum-(sum1*sum2/n)
  den=sqrt((sum1Sq-pow(sum1,2)/n)*(sum2Sq-pow(sum2,2)/n))
  if den==0: return 0
  r=num/den
  return r



#2.cuisine sim. matrix
def transformPrefs(user_ratings_dict):
  result = {}
  for person in user_ratings_dict:
      for item in user_ratings_dict[person]:
          result.setdefault(item, {})
          result[item][person] = user_ratings_dict[person][item]
  return result

def topMatches(user_ratings_dict,person,n=5,similarity=sim_pearson):
    scores=[(similarity(user_ratings_dict,person,other),other)
    for other in user_ratings_dict if other!=person]
    scores.sort()
    scores.reverse()
    return scores[0:n]

def calculateSimilarItems(user_ratings_dict, sim=sim_distance, n=10):
      # Create a dictionary of items showing
      # which other items they are most similar to.
      result = {}
      # Invert the preference matrix to be item-centric
      itemRatings = transformPrefs(user_ratings_dict)
      for item in itemRatings:
          # Find the most similar items to this one
          scores = topMatches(itemRatings,item,n,sim_distance)
          result[item] = scores
      return result

#3.select recomendation model user based
user=input("enter the user")
def getRecommendedItems(user_ratings_dict, itemSim, user):
  userRatings = user_ratings_dict[user]
  scores = {}
  totalSim ={}
# Loop over items rated by this user
  for item, rating in userRatings.items():
      # Loop over items similar to this one
          for similarity, item2 in itemSim[item]:
          # Ignore if this user has already rated this item
              if item2 in userRatings: continue
              # Weighted sum of rating times similarity
              scores.setdefault(item2, 0)
              scores[item2] += similarity * rating
              # Sum of all the similarities
              totalSim.setdefault(item2,0)
              totalSim[item2] += similarity
              # Divide each total score by total weighing to get an average
  rankings = [(score/totalSim[item], item) for item, score in scores.items()]
  # Return the rankings from highest to lowest
  rankings.sort(reverse=True)
  return rankings

#4.Take a number of recommendation

def makeRecommendations(user_ratings_dict, sim_distance, user, num_recommendations=5):
    userRatings = user_ratings_dict[user]
    scores = {}
    totalSim = {}

    for (item, rating) in userRatings.items():
        for (similarity, item2) in sim_distance[item]:
            if item2 in userRatings:
                continue
            scores.setdefault(item2, 0)
            scores[item2] += similarity * rating
            totalSim.setdefault(item2, 0)
            totalSim[item2] += similarity

    rankings = [(score / totalSim[item], item) for item, score in scores.items()]
    rankings.sort(reverse=True)
    recommendations = rankings[:num_recommendations]

    return recommendations

#5.select max number of recomendation
from math import sqrt

def listSimilarPersons(prefs, person, similarity_func=sim_distance, max_similar_persons=5):
    scores = [(similarity_func(prefs, person, other), other) for other in prefs if other != person]
    scores.sort(reverse=True)
    similar_persons = scores[:max_similar_persons]
    return similar_persons

#6.rec. for specific person
def makeRecommendations(user_ratings_dict, sim_distance, user, num_recommendations=5):
    """
     It makes suggestions to the user.

     Parameters:
     - user_ratings_dict: Dictionary containing user ratings data.
     - item_similarity_model: Precomputed similarity model.
     - user: The username to make suggestions.
     - num_recommendations: Number of recommendations to make.

     Returns:
     - recommendations: List of recommendations made to the user.
     """
    userRatings = user_ratings_dict[user]
    scores = {}
    totalSim = {}

    # Loop over items rated by this user
    for (item, rating) in userRatings.items():
        # Check if the item exists in the similarity model
        if item not in sim_distance:
            continue

        # Loop over items similar to this one
        for (similarity, item2) in sim_distance[item]:
            # Ignore if this user has already rated this item
            if item2 in userRatings:
                continue
            # Weighted sum of rating times similarity
            scores.setdefault(item2, 0)
            scores[item2] += similarity * rating
            # Sum of all the similarities
            totalSim.setdefault(item2, 0)
            totalSim[item2] += similarity

    # Divide each total score by total weighting to get an average
    rankings = [(score / totalSim[item], item) for item, score in scores.items()]

    # Return the top N recommendations
    rankings.sort(reverse=True)
    recommendations = rankings[:num_recommendations]

    return recommendations

# Main menu loop
while True:
    print("\nMain Menu:")
    print("1. Select a similarity metric (Euclidean or Pearson).")
    print("2. Display cuisine (item) similarity matrix.")
    print("3. Select a recommendation model (User-based or Item-based).")
    print("4. Set the maximum number of recommendations to be made.")
    print("5. List similar persons to a given person, together with their similarity scores.")
    print("6. Make a recommendation to a specific user.")
    print("7. Exit the program.")
    choice = input("Enter your choice (1-7): ")

    if choice == "1":
        choice = input("Enter your choice for similarity metric (Euclidean or Pearson)(1-2): ")
        if choice == "1":
          print("You selected 1. Select a Euclidean Similarity Metric.")
          person1 = input("İlk person ismini girin: ")
          person2 = input("İkinci person ismini girin: ")
          print(sim_distance(user_ratings_dict, person1 ,person2))
        else :
          print("You selected 1. Select a Pearson Similarity Metric.")
          person1 = input("İlk person ismini girin: ")
          person2 = input("İkinci person ismini girin: ")
          print(sim_pearson(user_ratings_dict, person1 ,person2))
    elif choice == "2":
          similar_items = calculateSimilarItems(user_ratings_dict, sim=sim_distance, n=10)

          print(similar_items)
          for item, scores in similar_items.items():
              print(f"{item}: {scores}")
    elif choice == "3":
        print("You selected 3. Select a recommendation model.")
        user=input("enter the user:")
        recommended_items = getRecommendedItems(user_ratings_dict, similar_items, user)
        print(recommended_items)
    elif choice == "4":
      print("You selected 4. Set the maximum number of recommendations to be made.")
      user = input("Enter the user name:")
      num_recommendations = int(input("Enter the maximum number of recommendations: "))
      user_recommendations = makeRecommendations(user_ratings_dict, similar_items,user, num_recommendations)
      print("\nRecommendations:")
      for score, item in user_recommendations:
          print(f"{item}: {score}")

    elif choice == "5":
        print("You selected 5. List similar persons to a given person, together with their similarity scores.")
        person=input("Enter the person name :")
        print("\nSimilar Persons:")
        for similarity, person in similar_persons:
              print(f"{person}: {similarity}")
    elif choice == "6":
        print("You selected 6. Make a recommendation to a specific user.")
        user = input("ente the user name:")
        user_recommendations = makeRecommendations(user_ratings_dict, similar_items,user, num_recommendations=5)

        print("\nÖnerilenler:")
        for score, item in user_recommendations:
                 print(f"{item}: {score}")
    elif choice == "7":
        print("Exiting the program. Goodbye!")
        break
    else:
        print("Invalid choice. Please enter a number between 1 and 7.")